### ISSUE TITLE
Mise à jour d'une matière

### ISSUE THREAD

**Issue by yassineazimani** [nashirow/EducationProject#2]
## Besoin

Nous souhaitons avoir la possibilité de modifier une matière au niveau de l'application.

**Comment by nashirow** [comment]
**Serait-il possible d'avoir un exemple ou des exemples pour la fonctionnalité "mise à jour d'une matière" ?**

**Comment by yassineazimani** [comment]
_Exemple(s) :_

* Je veux pouvoir mettre à jour la couleur de fond de la matière d'identifiant n°1
* Je veux pouvoir mettre à jour la description et le volume horaire hebdomadaire de la matière n°2

Les règles métiers de la création d'une matière sont les mêmes que celles de la modification d'une matière.
