### ISSUE TITLE
Suppression d'une matière

### ISSUE THREAD

**Issue by yassineazimani** [nashirow/EducationProject#3]
## Besoin

L'application doit nous donner la possibilité de supprimer une ou plusieurs matières.

**Comment by nashirow** [comment]
**Serait-il possible d'avoir un ou plusieurs exemples pour la fonctionnalité de suppression d'une matière ?**

**Comment by yassineazimani** [comment]
_Exemple(s) :_

* Je veux supprimer la matière d'identifiant n°1
* Je veux supprimer les matières d'identifiant n°1,2,3,4
