### ISSUE TITLE
Récupération des matières

### ISSUE THREAD

**Issue by yassineazimani** [nashirow/EducationProject#4]
## Besoin

Nous souhaitons avoir la possibilité de récupérer l'ensemble des matières stockées par l'application.

**Comment by nashirow** [comment]
J'ai quelques questions à poser au sujet de la récupération des matières. Il me faudrait également un ou plusieurs exemples pour chacune des questions.

1.  **Doit-on trier les matières dans un ordre spécifique ?**

2.  **Peut-on filtrer les matières ?**

3. **Peut-on paginer les matières ?**

**Comment by yassineazimani** [comment]
1. **Doit-on trier les matières dans un ordre spécifique ?**

Les matières doivent être récupérés selon un ordre alphabétique croissant sur le champ nom (nom de la matière).

_Exemple(s) :_

```json
[{name: "Français", id: 2, color: "#fff", backgroundColor: "#ddd"}, {name: "Mathématiques", id: 1, color: "#ddd", backgroundColor: "#fff"}]
```

2. **Peut-on filtrer les matières ?**

On peut filtrer les matières par nom, par couleur de police.

_Exemple(s) :_

* Je souhaite rechercher les matières dont le nom contient "mat"

* Je souhaite rechercher les matières dont la couleur de police est #fff

* Je souhaite rechercher les matières dont le nom contient "mat" et dont la couleur de police est #fff

3. **Peut-on paginer les matières ?**

Nous n'avons pas besoin de paginer les résultats.

**Comment by nashirow** [comment]
J'aimerai revenir sur le filtrage des matières par nom et couleur de police, que devons nous faire si les deux paramètres (nom et couleur de police) ne sont pas renseignés ou sont vides?

**Comment by yassineazimani** [comment]
On retourne dans ce cas là tous les résultats que l'on trouve dans la base de données. En effet, il faut s'imaginer sur une page web où on peut rechercher une matière par son nom et sa couleur. Si on renseigné le nom j aurai soit des résultats soit aucun résultat. Par contre, si je n indiqué rien au niveau du nom et de la couleur, il faut que tous les résultats se réaffichent au niveau de la page de résultats.

Conclusion : on retourne une liste qui a toutes les matières que l'application comporte.
